import { A, AR, F, F3, P, SAFETY_QUESTION, scene } from './scales.ts';
import type { CalcConfig } from './types.ts';

/**
 * 황혼 심화형 — 32문항 + 안전 문항. 7~9분.
 *
 * Built around the separation of dedication from constraint. The archetypal
 * late-life divorce is not a marriage that suddenly went wrong; it is a
 * marriage that has been held up by constraints — the children, the
 * neighbours, the household economics — collapsing at the moment those
 * constraints dissolve. Adding the two together hides that structure. Scoring
 * them apart and multiplying the gap is the only way it becomes visible,
 * which is why CNS carries weight 0 on its own and appears only in G.
 */
export const twilightDeep: CalcConfig = {
  type: 'twilight-deep',
  family: 'twilight',
  depth: 'deep',
  modelVersion: 2,
  path: '/twilight/deep',
  name: '황혼 부부 심화 진단',
  title: '황혼 부부 심화 진단',
  minutes: '약 8분',
  intro:
    '서른두 개의 질문으로, 오래 함께한 두 사람의 지금을 일곱 개의 구조로 나눠 봅니다. 특히 이 결혼을 지탱하는 것이 마음인지 조건인지를 따로 재는 데 무게를 둡니다. 조건은 시간이 지나면 하나씩 사라지기 때문입니다.',
  pronoun: { m: '아내', f: '남편', na: '배우자' },
  safety: SAFETY_QUESTION,
  steps: [
    { title: '요즘의 두 사람', caption: '먼저 지금의 느낌부터 봅니다.' },
    { title: '남아 있는 마음', caption: '무엇이 이 결혼을 지탱하는지 봅니다.' },
    { title: '말이 오가는 방식', caption: '오래된 부부일수록 말투는 습관이 됩니다.' },
    { title: '달라진 시간들', caption: '은퇴 이후에 새로 생긴 것들입니다.' },
    { title: '마지막 세 가지', caption: '' },
  ],
  dims: [
    { key: 'SAT', label: '만족과 유대', weight: 0.14, note: '지금 두 사람 사이의 온도' },
    { key: 'DED', label: '헌신', weight: 0.14, note: '함께 있고 싶은 마음' },
    {
      key: 'CNS',
      label: '제약 수준',
      weight: 0,
      levelOnly: true,
      note: '높다고 위험한 것이 아닙니다. 헌신이 낮을 때에만 위험이 됩니다',
    },
    { key: 'ADP', label: '상호작용', weight: 0.2, note: '말이 오가는 방식' },
    { key: 'ALT', label: '대안과 장벽', weight: 0.08, note: '혼자가 되는 그림의 선명도' },
    { key: 'STR', label: '후기의 압력', weight: 0.14, note: '은퇴·건강·돌봄·노후자금' },
    { key: 'MSI', label: '정리를 향한 걸음', weight: 0.12, note: '실제로 움직인 거리' },
  ],
  interactions: [
    {
      key: 'I',
      label: '압력 × 대처',
      a: 'STR',
      b: 'ADP',
      weight: 0.08,
      note: '은퇴와 돌봄이 주는 압력이 큰데 말이 오가는 방식까지 막혀 있으면, 두 가지가 곱해져서 작용합니다.',
    },
    {
      key: 'G',
      label: '헌신 없는 제약',
      a: 'DED',
      b: 'CNS',
      weight: 0.1,
      note: '남고 싶은 마음은 옅은데 떠나기 어려운 조건만 남아 있을 때 커지는 항입니다. 황혼 이혼의 전형적인 구조가 바로 이것입니다.',
    },
  ],
  flags: [
    {
      questionId: 'TD31',
      minChoiceIndex: 2,
      floor: 50,
      note: '이혼·별거·졸혼을 진지하게 이야기한 적이 있다는 응답은, 다른 응답과 별개로 지수를 끌어올립니다.',
    },
    {
      questionId: 'TD31',
      minChoiceIndex: 3,
      floor: 58,
      note: '별거 중이거나 사실상 각자 생활한 지 오래라는 응답은, 다른 응답과 별개로 지수를 끌어올립니다.',
    },
    {
      questionId: 'TD32',
      minChoiceIndex: 2,
      floor: 55,
      note: '재산·연금 분할이나 절차를 구체적으로 알아본 적이 있다는 응답은, 다른 응답과 별개로 지수를 끌어올립니다.',
    },
    {
      questionId: 'TD32',
      minChoiceIndex: 3,
      floor: 65,
      note: '전문가와 상담한 적이 있다는 응답은, 다른 응답과 별개로 지수를 끌어올립니다. 이미 실행의 영역에 들어와 있기 때문입니다.',
    },
  ],
  types: {
    x: { dim: 'DED', label: '헌신', cut: 50 },
    y: { dim: 'CNS', label: '제약', cut: 50 },
    quadrants: {
      ll: {
        code: 'partner',
        name: '동반자형',
        body: '붙잡는 조건이 없어도 함께 있을 관계입니다. 오래 함께한 부부에게 이것은 저절로 주어지는 상태가 아니라, 두 분이 만들어 온 결과에 가깝습니다.',
      },
      lh: {
        code: 'duty',
        name: '책임동행형',
        body: '마음과 책임이 함께 관계를 지탱하고 있습니다. 안정적이지만, 책임 쪽이 조금씩 더 무거워지면 마음 쪽이 가려집니다. 가끔은 의무가 아닌 시간을 따로 만들어 보세요.',
      },
      hl: {
        code: 'separate',
        name: '각자생활형',
        body: '붙잡는 것도, 붙잡고 싶은 마음도 옅어져 있습니다. 남은 시간을 어떻게 쓸지에 대해 정직한 대화가 필요한 시점입니다. 이 유형은 결론이 조용히, 그러나 빠르게 나는 편입니다.',
      },
      hh: {
        code: 'formality',
        name: '형식유지형',
        body: '관계를 지탱하는 것이 마음이 아니라 조건입니다. 조건은 시간이 지나면 하나씩 사라집니다 — 자녀의 독립처럼요. 조건이 사라지기 전에, 마음을 다시 쌓을지 정리를 준비할지 살펴볼 때입니다.',
      },
    },
  },
  questions: [
    // ── 스텝 1 · 요즘의 두 사람 ───────────────────────────────────────
    {
      id: 'TD1',
      dim: 'SAT',
      step: 1,
      factor: 'SATISFACTION',
      text: '요즘의 결혼 생활에, 나는 만족한다.',
      choices: AR,
    },
    {
      id: 'TD2',
      dim: 'SAT',
      step: 1,
      factor: 'BOND_CONFIDANT',
      text: '{배우자}는 여전히, 내 이야기를 나눌 상대다.',
      choices: AR,
    },
    {
      id: 'TD3',
      dim: 'SAT',
      step: 1,
      factor: 'EVENING_SCENE',
      text: '두 사람만 남는 저녁 시간은, 나에게?',
      choices: scene(
        ['편하고, 종종 즐겁다', 0],
        ['무난하다', 1],
        ['길게 느껴진다', 3],
        ['각자의 방에서 따로 보낸 지 오래다', 4],
      ),
    },
    {
      id: 'TD4',
      dim: 'SAT',
      step: 1,
      factor: 'SHARED_LAUGHTER',
      text: '지난 한 달 동안, {배우자}와 함께 웃은 날이 얼마나 있었나요?',
      choices: P,
    },
    {
      id: 'TD5',
      dim: 'SAT',
      step: 1,
      factor: 'RETROSPECT',
      text: '지난 세월을 돌아보면, 이 결혼은 나에게 잘한 선택이었다.',
      choices: AR,
    },

    // ── 스텝 2 · 남아 있는 마음 ───────────────────────────────────────
    {
      id: 'TD6',
      dim: 'DED',
      step: 2,
      factor: 'DED_CHOICE',
      text: '앞으로의 시간을 {배우자}와 보내는 것은, 의무가 아니라 내 선택이라고 느낀다.',
      choices: AR,
    },
    {
      id: 'TD7',
      dim: 'DED',
      step: 2,
      factor: 'DED_FUTURE_PLAN',
      text: '은퇴 후(또는 앞으로)의 계획에는?',
      choices: scene(
        ['둘이 함께 이야기해 둔 계획이 있다', 0],
        ['막연하지만 함께일 거라 생각한다', 1],
        ['각자의 계획이 따로 있다', 3],
        ['나 혼자만의 계획을 세워 두고 있다', 4],
      ),
    },
    {
      id: 'TD8',
      dim: 'DED',
      step: 2,
      factor: 'DED_CARE',
      text: '{배우자}가 아프면, 내가 곁을 지키는 것이 당연하다고 느낀다.',
      choices: AR,
    },
    {
      id: 'TD9',
      dim: 'DED',
      step: 2,
      factor: 'DED_EROSION',
      text: '요즘 나는 이 결혼을 "언제까지 유지할지"의 눈으로 바라보고 있다.',
      choices: A,
    },
    {
      id: 'TD10',
      dim: 'CNS',
      step: 2,
      factor: 'CNS_REASON',
      text: '이 결혼을 유지해 온 이유에 가장 가까운 것은?',
      choices: scene(
        ['함께 있는 것이 좋아서', 0],
        ['정과 의리로', 2],
        ['자녀와 주변 때문에', 3],
        ['헤어질 방법이 마땅치 않아서', 4],
      ),
    },
    {
      id: 'TD11',
      dim: 'CNS',
      step: 2,
      factor: 'CNS_EMPTYNEST',
      text: '자녀들이 완전히 독립하고 나면, 부부로 남아 있을 이유가 줄어든다는 생각이 든다.',
      choices: A,
    },
    {
      id: 'TD12',
      dim: 'CNS',
      step: 2,
      factor: 'CNS_PRACTICAL',
      text: '혼자가 됐을 때의 생활(살림, 건강 관리, 외로움)이 걱정되어 결혼을 유지하는 면이 있다.',
      choices: A,
    },
    {
      id: 'TD13',
      dim: 'CNS',
      step: 2,
      factor: 'CNS_SOCIAL',
      text: '주변에 이혼 사실이 알려지는 것이 부담스러워 참는 면이 있다.',
      choices: A,
    },

    // ── 스텝 3 · 말이 오가는 방식 ─────────────────────────────────────
    {
      id: 'TD14',
      dim: 'ADP',
      step: 3,
      factor: 'CON_CONTEMPT',
      text: '지난 한 달 동안, "당신이 뭘 알아", "평생 그렇게 살아라" 같은 무시하는 말이 — 어느 쪽에서든 — 오간 적이 있었나요?',
      choices: F,
    },
    {
      id: 'TD15',
      dim: 'ADP',
      step: 3,
      factor: 'CON_STONEWALL',
      text: '{배우자}가 말을 걸어올 때 나는 — 또는 내가 말을 걸 때 {배우자}는 — 보통?',
      choices: scene(
        ['하던 일을 멈추고 듣는 편이다', 0],
        ['건성으로 들어도 대화는 된다', 1],
        ['대답이 짧게 끊긴다', 3],
        ['필요한 말 외에는 대화가 없다', 4],
      ),
    },
    {
      id: 'TD16',
      dim: 'ADP',
      step: 3,
      factor: 'CON_WITHDRAW',
      text: '집안의 문제를 의논하려 하면?',
      choices: scene(
        ['마주 앉아 이야기가 된다', 0],
        ['미루다가도 결국 이야기한다', 1],
        ['한쪽이 "알아서 해"로 끝낸다', 3],
        ['꺼내는 것 자체를 포기했다', 4],
      ),
    },
    {
      id: 'TD17',
      dim: 'ADP',
      step: 3,
      factor: 'CON_PASTBLAME',
      text: '지난 한 달 동안, 지나간 일(수십 년 전 일 포함)을 다시 꺼내 탓하는 말이 — 어느 쪽에서든 — 나온 적이 있었나요?',
      choices: F,
    },
    {
      id: 'TD18',
      dim: 'ADP',
      step: 3,
      factor: 'CON_REPAIR',
      text: '말다툼이 커지려 할 때, 한쪽이 누그러뜨리는 말을 건네면?',
      choices: scene(
        ['대체로 받아들여진다', 0],
        ['가끔은 통한다', 1],
        ['"이제 와서"라며 통하지 않는다', 3],
        ['그런 시도가 사라진 지 오래다', 4],
      ),
    },
    {
      id: 'TD19',
      dim: 'ADP',
      step: 3,
      factor: 'CON_LOVEMAP',
      text: '요즘 {배우자}의 고민이나 관심사를, 나는?',
      choices: scene(
        ['구체적으로 안다', 0],
        ['대강은 안다', 1],
        ['잘 모른다', 3],
        ['궁금하지 않다', 4],
      ),
    },
    {
      id: 'TD20',
      dim: 'ADP',
      step: 3,
      factor: 'CON_MEALTALK',
      text: '지난 한 달 동안, 함께 밥을 먹으며 용건 없는 대화를 나눈 날이 얼마나 있었나요?',
      choices: P,
    },

    // ── 스텝 4 · 달라진 시간들 ────────────────────────────────────────
    {
      id: 'TD24',
      dim: 'STR',
      step: 4,
      factor: 'STR_RETIRE',
      text: '은퇴(또는 일에서 물러남) 이후, 함께 있는 시간이 늘면서?',
      choices: scene(
        ['아직 둘 다 은퇴 전이다', 0],
        ['오히려 사이가 좋아졌다', 0],
        ['큰 변화는 없다', 1],
        ['부딪히는 일이 늘었다', 3],
        ['서로를 피해 다니게 됐다', 4],
      ),
    },
    {
      id: 'TD25',
      dim: 'STR',
      step: 4,
      factor: 'STR_CARE',
      text: '나 또는 {배우자}의 건강 문제(간병 포함)가 부부 사이에 주는 부담은?',
      choices: scene(
        ['해당되는 일이 없다', 0],
        ['있지만, 함께 감당하고 있다', 1],
        ['한쪽에 쏠려 있고, 그쪽이 지쳐 간다', 3],
        ['이 문제로 원망이 쌓이고 있다', 4],
      ),
    },
    {
      id: 'TD26',
      dim: 'STR',
      step: 4,
      factor: 'STR_RETIRE_MONEY',
      text: '지난 세 달 동안, 노후 생활비 문제로 마음이 상하거나 다툰 적이 있었나요?',
      choices: F3,
    },
    {
      id: 'TD27',
      dim: 'STR',
      step: 4,
      factor: 'STR_CHILDREN',
      text: '자녀 문제(독립, 결혼, 지원)를 두고 두 사람의 생각은?',
      choices: scene(
        ['대체로 같다', 0],
        ['다르지만 조율이 된다', 1],
        ['달라서 자주 부딪힌다', 3],
        ['이 문제는 서로 꺼내지 않는다', 4],
      ),
    },
    {
      id: 'TD28',
      dim: 'STR',
      step: 4,
      factor: 'STR_CHORES',
      text: '요즘 집안일 분담은?',
      choices: scene(
        ['형편에 맞게 나누고 있다', 0],
        ['한쪽에 쏠렸지만 큰 불만은 없다', 1],
        ['한쪽에 쏠려 있고, 불만이 쌓이고 있다', 3],
        ['이 문제로 싸움이 반복된다', 4],
      ),
    },
    {
      id: 'TD29',
      dim: 'STR',
      step: 4,
      factor: 'STR_RESOURCE',
      text: '힘든 일이 있을 때, {배우자}는 나에게?',
      choices: scene(
        ['기댈 수 있는 사람이다', 0],
        ['부담을 주지는 않는 사람이다', 1],
        ['말해도 소용없는 사람이다', 3],
        ['힘든 일의 원인일 때가 많다', 4],
      ),
    },
    {
      id: 'TD21',
      dim: 'ALT',
      step: 4,
      factor: 'ALT_VIABLE',
      text: '혼자 살게 되더라도, 내 일상(식사, 건강, 사람 관계)은 꾸려 갈 수 있을 것 같다.',
      choices: A,
    },
    {
      id: 'TD22',
      dim: 'ALT',
      step: 4,
      factor: 'ALT_REHEARSE',
      text: '지난 세 달 동안, 황혼이혼이나 졸혼 이후의 생활을 구체적으로 알아보거나 상상해 본 적이 있었나요?',
      choices: F3,
    },
    {
      id: 'TD23',
      dim: 'ALT',
      step: 4,
      factor: 'ALT_BETTER',
      text: '남은 시간을 생각하면, 지금처럼 사는 것보다 따로 사는 편이 낫겠다는 생각이 든다.',
      choices: A,
    },

    // ── 스텝 5 · 마지막 세 가지 ───────────────────────────────────────
    {
      id: 'TD30',
      dim: 'MSI',
      step: 5,
      factor: 'MSI_THINK',
      text: '황혼이혼(또는 졸혼)에 대해서는?',
      choices: scene(
        ['생각해 본 적 없다', 0],
        ['지나가듯 생각해 본 적 있다', 1],
        ['구체적인 시점을 두고 반복해서 생각한다', 3],
        ['준비를 하고 있다', 4],
      ),
    },
    {
      id: 'TD31',
      dim: 'MSI',
      step: 5,
      factor: 'MSI_VOICE',
      text: '{배우자}나 자녀 앞에서 이혼·별거·졸혼 이야기를 꺼낸 적이 있나요?',
      choices: scene(
        ['없다', 0],
        ['홧김에 나온 적 있다', 2],
        ['진지하게 이야기했다', 3],
        ['별거 중이거나, 사실상 각자 생활한 지 오래다', 4],
      ),
    },
    {
      id: 'TD32',
      dim: 'MSI',
      step: 5,
      factor: 'MSI_PREPARE',
      text: '재산 분할, 연금 분할, 이혼 절차 등을 알아본 적이 있나요?',
      choices: scene(
        ['없다', 0],
        ['방송이나 기사에서 본 정도', 1],
        ['내 경우에 대입해 구체적으로 알아봤다', 3],
        ['전문가와 상담을 했다', 4],
      ),
    },
  ],
};
